FROM node:18

# Install missing system libraries
RUN apt-get update && apt-get install -y libatomic1

# Set working directory
WORKDIR /src

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy source code
COPY . .

# Build your app
RUN npm run build

# Start command
CMD ["npm", "start"]
